require("dotenv").config();
module.exports={
    PORT:process.env.PORT,
    DATABASE_URL:process.env.DATABASE_URL,
    JWT_SECRET:process.env.JWT_SECRET,
    NODE_ENV:process.env.NODE_ENV,
    key_id:process.env.key_id,
    key_secret:process.env.key_secret
}